### ISSUE TITLE
Banyak muncul notice error ketika plugin diaktifkan

### ISSUE THREAD

**Issue by nugjogjaweb** [yeriepiscesa/cf7-send-wa#1]
Sebelumnya terima kasih sekali anda telah mendevelop plugin ini, semoga tetap dilanjutkan pengembangannya, saya sudah coba menggunakannya meskipun di website demo. 

Hanya saja ketika saya mengaktifkan plugin ini banyak notice error yang muncul di halaman setting plugin dan di halaman checkout, untuk screenshotnya dibawah ini (saya upload di prnt.sc)

1) Halaman setting plugin. https://prnt.sc/t9j3sa
2) Halaman checkout https://prnt.sc/t9j4ea

Secara fungsi memang tidak ada masalah tapi alangkah baiknya jika notice error diperbaiki. 

Semoga update selanjutnya bisa diperbaiki, terima kasih.

**Comment by yeriepiscesa** [comment]
Terima kasih sudah mencoba plugin ini, notice error sudah diperbaiki. 
Silahkan dicoba kembali.
