### ISSUE TITLE
Auto respond WA message (using third party service).

### ISSUE THREAD

**Issue by srakl** [yeriepiscesa/cf7-send-wa#3]
Hi

Quick Question. 

1. The Auto respond WA message (using third party service).

Under "To Number" i can use [tel-306], the number of the person filling up the form right? To send him a "thank you" whatsapp message?

I'm about to sign up with Twilio so want to make sure this will work.

2. Autoresponder needs Twilio, or is Whatsapp Business enough?

Thank you.

**Comment by yeriepiscesa** [comment]
Hi, 
1. Yes, as long as [tel-306] is filled with a phone number
2. It needs Twilio's API for sending

**Comment by srakl** [comment]
Ok i put in my Account SID and Auth Token.
enabled "Use WhatsApp Autorespond"

but when i submit the contact form 7, i don't get a whatsapp message. Any idea what im missing? Thank you

**Comment by yeriepiscesa** [comment]
I have no clue, please see the video below for working scenario.
https://streamable.com/u24cas
