### ISSUE TITLE
Exclude lines that are blank

### ISSUE THREAD

**Issue by mikeloomans** [yeriepiscesa/cf7-send-wa#4]
Does the script also has a function to exclude lines that are blank?

**Comment by yeriepiscesa** [comment]
Unfortunately it doesn't, since it still utilizes WPCF7_MailTaggedText class to render template tags. However it's a good idea, let see what can I do in the next release.

**Comment by mikeloomans** [comment]
Great! Please let me know :) great system, thnx!

**Comment by yeriepiscesa** [comment]
new release has arrived... please check for new tag [cf7sendwa-skip-empty] .... [/cf7sendwa-skip-empty], please take a look.
example:
[cf7sendwa-skip-empty]
Phone number : [phone-number]
[/cf7sendwa-skip-empty]

**Comment by mikeloomans** [comment]
[cf7sendwa-skip-empty] [AantalBiefstuk] kg *Kogelbiefstuk* [/cf7sendwa-skip-empty]

The field "AantalBiefstuk" is not showing when its blank but also when it has data, so that doesn't work like it should. Suggestion?

**Comment by yeriepiscesa** [comment]
Relase 0.12.5 fix this issue.
