### ISSUE TITLE
Plugin tidak berfungsi dengan elementor

### ISSUE THREAD

**Issue by gusleo** [yeriepiscesa/cf7-send-wa#5]
Terima kasih sebelumnya untuk plugin yang luar biasa ini,

Saya menggunakan HT Contact Form 7 untuk meng-import Form ke dalam halaman elementor, namun ketika mengklik tombol Kirim, WA link yang biasanya di-genarete tidak terjadi.

Adakah cara untuk memperbaiki ini?

**Comment by yeriepiscesa** [comment]
Kemungkinan shortcode yang digenerate dari plugin itu (HT Contact Form 7) bukan [contact-form-7-wa], shortcode cf7sendwa (dengan akhiran -wa)
